vars.card = {
  default: {
    style: 'stacked',
    size: 'large',
    url: '#',
    image: '<img width="4000" height="2666" src="https://www.hrw.org/sites/default/files/styles/embed_xxl/public/media_2024/04/202403africa_Rwanda_CorinnePhotoTutsi.jpg?itok=zQ021UuA" alt="House with the word &quot;Tutsi&quot; written in chalk on the outside wall" />',
    date: 'April 2, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Rwanda: Genocide Archives Released',
    flair: 'Most Read',
    teaser: 'Human Rights Watch is releasing a series of archives highlighting the extraordinary efforts of human rights defenders in Rwanda and abroad, to warn about the planned 1994 genocide and attempt to stop the killings. The documents painfully illustrate leading international actors’ refusal to acknowledge the slaughter of more than half a million people and act to end it.',
  },
  stacked: {
    style: 'stacked',
  } ,
  sidebyside: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2024/04/202404asia_philippines_sebastian_duterte.jpg?h=cc9f8164&amp;itok=CSPBWw2t" alt="Sebastian Duterte, currently the mayor of Davao City, delivers a speech at a campaign rally in Davao City, the &nbsp;hometown of his father, then-President Rodrigo Duterte, May 10, 2019." loading="lazy" class="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 2, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Philippines: New ‘Drug War’ Declared in Davao City',
    flair: 'Breaking News Statement',
    teaser: false,
  },
  sidebyside2: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2024/04/202404eca_russia_tajik_attacks.jpg?h=d454c46d&amp;itok=2gefLIL_" alt="Two work migrants from Central Asia&nbsp;in&nbsp;Moscow, Russia, April 14, 2023." loading="lazy" class="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 5, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Russia: In Wake of Concert Attack, Central Asians at Risk',
    teaser: false,
  },
  sidebyside3: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2024/04/202404mena_palestine_gaza_engineers_building_child.jpg?h=a5779a7e&amp;itok=9OXqsIiz" alt="In the rubble of the Engineers’ Building, Karam al-Sharif, an UNRWA employee, holds one of his 18-month-old twin boys killed in the October 31 Israeli airstrike on the building that killed at least 106 civilians, including 5 of his children and 5 other relatives." loading="lazy" className="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 4, 2024',
    type: 'Report',
    heading_level: 'h3',
    title: 'Gaza: Israeli Strike Killing 106 Civilians an Apparent War Crime',
    flair: false,
    teaser: false,
  },
  sidebyside4: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2023/06/202306afr_kenya_uganda_lgbtq_refugees.jpg?h=90d10537&amp;itok=KElHSPcA" alt="Gay Ugandan refugees who fled from their country to neighboring Kenya, return after shopping for food in Nairobi, Kenya, June 11, 2020." loading="lazy" class="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 4, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Uganda: Court Upholds Anti-Homosexuality Act  ',
    flair: false,
    teaser: false,
  },

};
