vars.card = {
  default: {
    style: 'stacked',
    size: 'large',
    url: '#',
    image: '<img width="4000" height="2666" src="https://www.hrw.org/sites/default/files/styles/embed_xxl/public/media_2024/04/202403africa_Rwanda_CorinnePhotoTutsi.jpg?itok=zQ021UuA" alt="House with the word &quot;Tutsi&quot; written in chalk on the outside wall" />',
    date: 'April 2, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Rwanda: Genocide Archives Released',
    flair: 'Most Read',
    teaser: 'Human Rights Watch is releasing a series of archives highlighting the extraordinary efforts of human rights defenders in Rwanda and abroad, to warn about the planned 1994 genocide and attempt to stop the killings. The documents painfully illustrate leading international actors’ refusal to acknowledge the slaughter of more than half a million people and act to end it.',
  },
  stacked: {
    style: 'stacked',
  } ,
  sidebyside: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2024/04/202404asia_philippines_sebastian_duterte.jpg?h=cc9f8164&amp;itok=CSPBWw2t" alt="Sebastian Duterte, currently the mayor of Davao City, delivers a speech at a campaign rally in Davao City, the &nbsp;hometown of his father, then-President Rodrigo Duterte, May 10, 2019." loading="lazy" class="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 2, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Philippines: New ‘Drug War’ Declared in Davao City',
    flair: 'Breaking News Statement',
    teaser: false,
  },
  sidebyside2: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2024/04/202404eca_russia_tajik_attacks.jpg?h=d454c46d&amp;itok=2gefLIL_" alt="Two work migrants from Central Asia&nbsp;in&nbsp;Moscow, Russia, April 14, 2023." loading="lazy" class="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 5, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Russia: In Wake of Concert Attack, Central Asians at Risk',
    teaser: false,
  },
  sidebyside3: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2024/04/202404mena_palestine_gaza_engineers_building_child.jpg?h=a5779a7e&amp;itok=9OXqsIiz" alt="In the rubble of the Engineers’ Building, Karam al-Sharif, an UNRWA employee, holds one of his 18-month-old twin boys killed in the October 31 Israeli airstrike on the building that killed at least 106 civilians, including 5 of his children and 5 other relatives." loading="lazy" className="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 4, 2024',
    type: 'Report',
    heading_level: 'h3',
    title: 'Gaza: Israeli Strike Killing 106 Civilians an Apparent War Crime',
    flair: false,
    teaser: false,
  },
  sidebyside4: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2023/06/202306afr_kenya_uganda_lgbtq_refugees.jpg?h=90d10537&amp;itok=KElHSPcA" alt="Gay Ugandan refugees who fled from their country to neighboring Kenya, return after shopping for food in Nairobi, Kenya, June 11, 2020." loading="lazy" class="card__image unloaded w-auto" width="400" height="225">',
    date: 'April 4, 2024',
    type: 'News Release',
    heading_level: 'h3',
    title: 'Uganda: Court Upholds Anti-Homosexuality Act  ',
    flair: false,
    teaser: false,
  },
  ar: {
    style: 'stacked',
    size: 'large',
    url: '#',
    image: '<img width="720" height="480" src="https://www.hrw.org/sites/default/files/media_2021/02/202002mena_uae_jordan_etoum.jpg" alt="Ahmed Etoum" />',
    date: 'مارس/آذار 6, 2024',
    type: 'تصريحات',
    title: 'بيان مشترك: وفاة والدة الناشط الأردني أحمد العتوم أثناء قضائه عقوبة السَّجن 10 سنوات في الإمارات بسبب منشورات "فيسبوك"',
    flair: 'الأكثر قراءة',
    teaser: 'قالت "منظمة منا لحقوق الإنسان"، و"مركز مناصرة معتقلي الإمارات"، و"منظمة العفو الدولية"، و"هيومن رايتس ووتش" اليوم إن على الإمارات أن تخلي سبيل الناشط الأردني أحمد العتوم المسجون تعسفا وتلغي الحكم الصادر بحقه. توفيت والدة العتوم في 10 فبراير/شباط 2024 من دون أن تودع ابنها.',
  },
  ar_sidebyside: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/embed_xxl/public/media_2024/04/202404mena_palestine_family_Khirbet_Zanuta.jpg?itok=SVo-_-jF" alt="A family packs up their belongings" loading="lazy" class="card__image unloaded w-auto" width="946" height="631">',
    date: 'أبريل/نيسان 17, 2024',
    type: 'بيان صحفي',
    title: 'الضفة الغربية: إسرائيل مسؤولة عن تصاعد عنف المستوطنين',
    flair: 'بيان الأخبار العاجلة',
    teaser: false,
  },
  ar_sidebyside2: {
    style: 'sidebyside',
    size: 'small',
    image: '<img src="https://www.hrw.org/sites/default/files/styles/embed_xxl/public/media_2024/04/202404mena_palestine_gaza_starvation_children.JPG?itok=9TFD_nq1" alt="طفلان فلسطينيان يعانيان من سوء التغذية يتلقيان العلاج في مركز طبي في رفح، جنوب قطاع غزة، 4 مارس/آذار 2024." loading="lazy" class="card__image unloaded w-auto" width="946" height="618">',
    date: 'أبريل/نيسان 9, 2024',
    type: 'تقرير',
    heading_level: 'h3',
    title: 'غزة: التجويع الذي تفرضه إسرائيل يقتل الأطفال',
    flair: 'الأكثر قراءة',
    teaser: false,
  },
  ar_sidebyside3: {
    style: 'sidebyside',
    size: 'small',
    image: '<img class="report-header__image w-full order-2" src="https://www.hrw.org/sites/default/files/styles/16x9_large/public/media_2021/04/202104mena_israelpalestine_barrier.jpg?h=8fd0f494&amp;itok=VUqoI3CI" alt="A boy runs alongside a tall concrete wall" width="700" height="393" loading="lazy">',
    date: 'أبريل/نيسان 27, 2021',
    type: 'تقرير',
    heading_level: 'h3',
    title: 'تجاوزوا الحد',
    flair: false,
    teaser: false,
  },
  ar_sidebyside4: {
    style: 'sidebyside',
    size: 'small',
    image: '<img width="946" height="532" src="https://www.hrw.org/sites/default/files/styles/embed_xxl/public/media_2023/10/202310mena_Israel_Palestine_dashcam_stills.jpg?itok=4fAFUr1R" alt="202310mena_Israel_Palestine_dashcam_stills">',
    date: 'أكتوبر/تشرين الأول 18, 2023',
    type: ' بيان صحفي ',
    heading_level: 'h3',
    title: 'إسرائيل/فلسطين: التحقق من فيديوهات لهجمات قادتها حماس',
    flair: false,
    teaser: false,
  },

};
