vars.hero = {
  default: {
    variant: "",
    image: "<img alt='FPO' src='https://www.hrw.org/sites/default/files/styles/embed_xxl/public/media_2024/03/202403lgbt_videothumbnail_mex.jpg' width='2250' height='1264'/>",
    eyebrow: "News Release",
    date: "April 1, 2024",
    headline: "Mexico: Guanajuato Should Legally Recognize Trans Identities",
    body: "<p>Trans people in the Mexican state of Guanajuato suffer economic, medical, and labor discrimination, and other onerous legal impediments because the state has no process for issuing identity documents consistent with their gender. A new documentary follows the stories of two transgender women who have fought to have their gender and names legally recognized in Guanajuato.</p>",
    package: false,
    links: [
      {url: "#", text: "Read the report"},
      {url: "#", text: "Watch the video"},
      {url: "#", text: "Donate"},
      {url: "#", text: "Sign the petition"},
    ],
  },
  breaking: {
    variant: "breaking",
    eyebrow: "Breaking News",
  },
  es: {
    eyebrow: "Comunicado de prensa",
    date: "1 de abril de 2024\n",
    headline: "México: Guanajuato debería reconocer legalmente las identidades trans ",
    body: "<p>Las personas trans en el estado mexicano de Guanajuato sufren discriminación en los ámbitos económico, laboral y de salud, así como importantes impedimentos legales, porque el estado no cuenta con un proceso para emitir documentos de identidad acordes con su género, señaló Human Rights Watch en un documental difundido hoy.</p>",
  },
  reverse: {
    variant: "reverse",
    eyebrow: "Featured Investigation",
    date: "",
    headline: "Iran: Security Forces Rape, Torture, Detainees",
    image: '<img src="https://www.hrw.org/sites/default/files/media_2024/04/202404mena_iran_detainee_representation.jpg" width="4000" height="2697" alt="Silhouette of a woman (representation)" loading="lazy">',
    body: "",
    package: "",
    links: [],
  },
  reverse_ar: {
    variant: "reverse",
    eyebrow: "أبريل/نيسان 22, 2024",
    date: "",
    headline: "إيران: قوات الأمن تغتصب محتجزات ومحتجزين وتعذّبهم",
    image: '<img src="https://www.hrw.org/sites/default/files/media_2024/04/202404mena_iran_detainee_representation.jpg" width="4000" height="2697" alt="Silhouette of a woman (representation)" loading="lazy">',
    body: "",
    package: "",
    links: [],
  },
};